### ISSUE TITLE
Typescript mismatch with `useLoadable`

### ISSUE THREAD

**Issue by xavdid** [Airtable/blocks#3]
In the default youtube example, `useLoadable` used as follows:

https://github.com/Airtable/blocks/blob/7c1ead6cafc8eac3d107bcae8e6f1643452a7cbc/examples/youtube-preview-block/frontend/index.js#L34

I'm getting a TS error:

![](https://zappy.zapier.com/4b8a699b6512a288cfd26bd2a6883edf.png)

The `useLoadable` source seems to show that the second param should indeed be an `object`, not a `string[]`:

https://github.com/Airtable/blocks/blob/7c1ead6cafc8eac3d107bcae8e6f1643452a7cbc/packages/sdk/src/ui/use_loadable.ts#L112-L114

**Comment by minicat** [comment]
@xavdid Thanks for your patience! All of the example should be back now.
